site_name: ecs-utdevents documentation
nav:
  - index.md
  - about.md
  - 'Developers':
    - 'Front-End': 'frontend.md'
    - 'Back-End': 'backend.md'
    - 'API Documentation': 'api_documentation.md'
    -  admin.md

markdown_extensions:
  - admonition
  - pymdownx.superfences

theme: readthedocs